In [6]:
%load_ext autoreload
%autoreload 2
#Reloads import libraries before every piece of code is run so that changes in function.py reflect immediately


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import time
import random
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

#import functions

from dataset_import import prepareFMNISTData, prepareRailwayData, prepareMedicalData
from distance_metrics import euclideanDistance, manhattenDistance, chebyschevDistance
from PCA import PCA, project
from evaluation_metrics import accuracy, precision, recall, f1Score

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Assignment
Algorithms to implement: 
- Linear Models:
- Logistic Models 
- Perceptron
- FLDA
- Multi-Class Discriminative Models
- Support Vector Machines

# Linear Models
We'll try to find an aribitrary hyperplane that works for linearly seperable data

##### Kernel:
    - Can project data onto a greater polynomial space
    - Can also try to reduce the data to a small dimensional subspace [PCA]
##### Training:
    - Solve Normal Equations of W*
    - Search for W* using Gradient Descent
    - Search for W* using Perceptron algorithm    
##### Expectation:
    - When data is projected upward onto a very large polynomial superspace, the data will become linearly seperable and hence we'll be able to find a good hyperplane : Overfitting
    - When data is projected inward onto a very small subspace, there is no linear seperability and these algos stop working
    
    

# Adaptations
When the data isn't perfectly linearly seperable, say there is a region in between that contains both classes, then we need quantifications of linear seperability, and updates in our algorithms.
##### Logistic Models
    - Sigmoid of WX is the cost of misclassification, rather than 1 as for linear model (under both 0-1 and MS loss)
    VERIFY
    - Works best when class-conditional densities are gaussians
    - reduces to a linear model for linearly seperable data

##### Fischer Discriminant Analysis
    - Is another way of choosing the classifying hyperplane. This method tries to maximize the projected intra-class variance with respect to the projected inter-class variance.

##### Support Vector Machines
    - Choose that hyper plane that maximizes distance from points, and also seperates them.


In [3]:
def gradientDescent(x, y, W, alpha, numIterations):
    m = x.shape[0]
    for i in range(0, numIterations):
        hypothesis = np.dot(x, W)
        loss = hypothesis - y
        cost = np.sum(loss ** 2) / (2 * m)
        print("Iteration %d | Cost: %f" % (i, cost))
        # avg gradient per example
        gradient = np.dot(x.transpose(), loss) / m
        # update
        W = W - alpha * gradient
    return W    
    
    
    
def genData(numPoints, bias, variance):
    x = np.zeros(shape=(numPoints, 2))
    y = np.zeros(shape=numPoints)
    # basically a straight line with added noise
    for i in range(0, numPoints):
        x[i][0] = 1
        x[i][1] = i
        y[i] = (i + bias) + random.uniform(0, 1) * variance
    return x, y

x, y = genData(100, 25, 10)
m, n = np.shape(x)
numIterations= 10000
alpha = 0.0005
W = np.ones(n)
W = gradientDescent(x, y, W, alpha, numIterations)
print(W)

Iteration 0 | Cost: 424.689097
Iteration 1 | Cost: 239.579281
Iteration 2 | Cost: 163.238583
Iteration 3 | Cost: 131.745803
Iteration 4 | Cost: 118.744817
Iteration 5 | Cost: 113.368410
Iteration 6 | Cost: 111.135791
Iteration 7 | Cost: 110.199428
Iteration 8 | Cost: 109.797545
Iteration 9 | Cost: 109.616043
Iteration 10 | Cost: 109.525414
Iteration 11 | Cost: 109.472257
Iteration 12 | Cost: 109.434555
Iteration 13 | Cost: 109.403230
Iteration 14 | Cost: 109.374538
Iteration 15 | Cost: 109.346935
Iteration 16 | Cost: 109.319786
Iteration 17 | Cost: 109.292827
Iteration 18 | Cost: 109.265952
Iteration 19 | Cost: 109.239114
Iteration 20 | Cost: 109.212296
Iteration 21 | Cost: 109.185490
Iteration 22 | Cost: 109.158693
Iteration 23 | Cost: 109.131904
Iteration 24 | Cost: 109.105122
Iteration 25 | Cost: 109.078348
Iteration 26 | Cost: 109.051579
Iteration 27 | Cost: 109.024818
Iteration 28 | Cost: 108.998064
Iteration 29 | Cost: 108.971316
Iteration 30 | Cost: 108.944575
Iteration 31 | Cos

Iteration 1472 | Cost: 76.655370
Iteration 1473 | Cost: 76.636828
Iteration 1474 | Cost: 76.618290
Iteration 1475 | Cost: 76.599757
Iteration 1476 | Cost: 76.581228
Iteration 1477 | Cost: 76.562705
Iteration 1478 | Cost: 76.544186
Iteration 1479 | Cost: 76.525671
Iteration 1480 | Cost: 76.507162
Iteration 1481 | Cost: 76.488657
Iteration 1482 | Cost: 76.470157
Iteration 1483 | Cost: 76.451661
Iteration 1484 | Cost: 76.433170
Iteration 1485 | Cost: 76.414684
Iteration 1486 | Cost: 76.396203
Iteration 1487 | Cost: 76.377726
Iteration 1488 | Cost: 76.359254
Iteration 1489 | Cost: 76.340786
Iteration 1490 | Cost: 76.322324
Iteration 1491 | Cost: 76.303866
Iteration 1492 | Cost: 76.285412
Iteration 1493 | Cost: 76.266964
Iteration 1494 | Cost: 76.248520
Iteration 1495 | Cost: 76.230080
Iteration 1496 | Cost: 76.211646
Iteration 1497 | Cost: 76.193216
Iteration 1498 | Cost: 76.174791
Iteration 1499 | Cost: 76.156370
Iteration 1500 | Cost: 76.137954
Iteration 1501 | Cost: 76.119543
Iteration 

Iteration 3277 | Cost: 49.799380
Iteration 3278 | Cost: 49.787650
Iteration 3279 | Cost: 49.775924
Iteration 3280 | Cost: 49.764201
Iteration 3281 | Cost: 49.752480
Iteration 3282 | Cost: 49.740763
Iteration 3283 | Cost: 49.729049
Iteration 3284 | Cost: 49.717337
Iteration 3285 | Cost: 49.705629
Iteration 3286 | Cost: 49.693923
Iteration 3287 | Cost: 49.682221
Iteration 3288 | Cost: 49.670521
Iteration 3289 | Cost: 49.658825
Iteration 3290 | Cost: 49.647131
Iteration 3291 | Cost: 49.635440
Iteration 3292 | Cost: 49.623753
Iteration 3293 | Cost: 49.612068
Iteration 3294 | Cost: 49.600386
Iteration 3295 | Cost: 49.588707
Iteration 3296 | Cost: 49.577031
Iteration 3297 | Cost: 49.565359
Iteration 3298 | Cost: 49.553689
Iteration 3299 | Cost: 49.542022
Iteration 3300 | Cost: 49.530358
Iteration 3301 | Cost: 49.518697
Iteration 3302 | Cost: 49.507039
Iteration 3303 | Cost: 49.495383
Iteration 3304 | Cost: 49.483731
Iteration 3305 | Cost: 49.472082
Iteration 3306 | Cost: 49.460436
Iteration 

Iteration 5091 | Cost: 32.744605
Iteration 5092 | Cost: 32.737202
Iteration 5093 | Cost: 32.729801
Iteration 5094 | Cost: 32.722403
Iteration 5095 | Cost: 32.715006
Iteration 5096 | Cost: 32.707611
Iteration 5097 | Cost: 32.700217
Iteration 5098 | Cost: 32.692826
Iteration 5099 | Cost: 32.685437
Iteration 5100 | Cost: 32.678049
Iteration 5101 | Cost: 32.670663
Iteration 5102 | Cost: 32.663280
Iteration 5103 | Cost: 32.655898
Iteration 5104 | Cost: 32.648518
Iteration 5105 | Cost: 32.641139
Iteration 5106 | Cost: 32.633763
Iteration 5107 | Cost: 32.626389
Iteration 5108 | Cost: 32.619016
Iteration 5109 | Cost: 32.611645
Iteration 5110 | Cost: 32.604276
Iteration 5111 | Cost: 32.596910
Iteration 5112 | Cost: 32.589544
Iteration 5113 | Cost: 32.582181
Iteration 5114 | Cost: 32.574820
Iteration 5115 | Cost: 32.567460
Iteration 5116 | Cost: 32.560103
Iteration 5117 | Cost: 32.552747
Iteration 5118 | Cost: 32.545393
Iteration 5119 | Cost: 32.538041
Iteration 5120 | Cost: 32.530691
Iteration 

Iteration 6595 | Cost: 23.487978
Iteration 6596 | Cost: 23.482924
Iteration 6597 | Cost: 23.477871
Iteration 6598 | Cost: 23.472819
Iteration 6599 | Cost: 23.467769
Iteration 6600 | Cost: 23.462720
Iteration 6601 | Cost: 23.457672
Iteration 6602 | Cost: 23.452626
Iteration 6603 | Cost: 23.447580
Iteration 6604 | Cost: 23.442536
Iteration 6605 | Cost: 23.437494
Iteration 6606 | Cost: 23.432452
Iteration 6607 | Cost: 23.427412
Iteration 6608 | Cost: 23.422373
Iteration 6609 | Cost: 23.417336
Iteration 6610 | Cost: 23.412299
Iteration 6611 | Cost: 23.407264
Iteration 6612 | Cost: 23.402231
Iteration 6613 | Cost: 23.397198
Iteration 6614 | Cost: 23.392167
Iteration 6615 | Cost: 23.387137
Iteration 6616 | Cost: 23.382109
Iteration 6617 | Cost: 23.377081
Iteration 6618 | Cost: 23.372055
Iteration 6619 | Cost: 23.367030
Iteration 6620 | Cost: 23.362007
Iteration 6621 | Cost: 23.356985
Iteration 6622 | Cost: 23.351964
Iteration 6623 | Cost: 23.346944
Iteration 6624 | Cost: 23.341925
Iteration 

Iteration 8470 | Cost: 15.945882
Iteration 8471 | Cost: 15.942741
Iteration 8472 | Cost: 15.939601
Iteration 8473 | Cost: 15.936462
Iteration 8474 | Cost: 15.933323
Iteration 8475 | Cost: 15.930186
Iteration 8476 | Cost: 15.927049
Iteration 8477 | Cost: 15.923913
Iteration 8478 | Cost: 15.920777
Iteration 8479 | Cost: 15.917643
Iteration 8480 | Cost: 15.914509
Iteration 8481 | Cost: 15.911376
Iteration 8482 | Cost: 15.908244
Iteration 8483 | Cost: 15.905113
Iteration 8484 | Cost: 15.901983
Iteration 8485 | Cost: 15.898853
Iteration 8486 | Cost: 15.895724
Iteration 8487 | Cost: 15.892596
Iteration 8488 | Cost: 15.889469
Iteration 8489 | Cost: 15.886342
Iteration 8490 | Cost: 15.883216
Iteration 8491 | Cost: 15.880092
Iteration 8492 | Cost: 15.876967
Iteration 8493 | Cost: 15.873844
Iteration 8494 | Cost: 15.870722
Iteration 8495 | Cost: 15.867600
Iteration 8496 | Cost: 15.864479
Iteration 8497 | Cost: 15.861359
Iteration 8498 | Cost: 15.858239
Iteration 8499 | Cost: 15.855121
Iteration 

In [8]:
def get_one_hot(targets, nb_classes):
    res = np.eye(nb_classes)[np.array(targets).reshape(-1)]
    return res.reshape(list(targets.shape)+[nb_classes])

In [166]:
def gradientDescentMultiClass(x, y, W, alpha, numIterations):
    m = x.shape[0]
    for i in range(0, numIterations):
        hypothesis = np.exp(np.dot(x, W))
        rowsum = np.sum(hypothesis, axis=1)
        hypthesis = hypothesis/rowsum[:, None]
        print(hypothesis)
        loss = hypothesis-y
        cost = np.sum(loss ** 2) / (2 * m)
        print("Iteration %d | Cost: %f" % (i, cost))
        # avg gradient per example
        gradient = np.dot(x.transpose(), loss) / m
        # update
        W = W - alpha * gradient
    return W  

In [167]:
def multiClassLogisticRegression(X, y):
    numClasses = y.shape[1]
    numFeatures = X.shape[1]
    X = np.hstack((np.array(np.ones((X.shape[0],1))),X))
    W = np.ones((numFeatures+1, numClasses))
    return gradientDescentMultiClass(X, y, W, 0.1, 1000)

In [168]:
(X_train, y_train, X_val, y_val, X_test, y_test) = prepareMedicalData()
y_train = get_one_hot(y_train, 3)
X_test = np.hstack((np.array(np.ones((X_test.shape[0],1))),X_test))
W = multiClassLogisticRegression(X_train, y_train)


[[ 31.26545617  31.26545617  31.26545617]
 [205.34625689 205.34625689 205.34625689]
 [196.88196826 196.88196826 196.88196826]
 ...
 [143.04271918 143.04271918 143.04271918]
 [ 34.47602537  34.47602537  34.47602537]
 [724.34241589 724.34241589 724.34241589]]
Iteration 0 | Cost: 66122.555817
[[1.01986437e-25 9.54060730e-26 9.65180424e-26]
 [9.32928735e-44 7.74333213e-44 7.88594205e-44]
 [2.01641586e-43 1.55538256e-43 1.90541350e-43]
 ...
 [3.01974443e-39 2.59860677e-39 2.73578409e-39]
 [6.16539620e-28 5.74416777e-28 5.32437418e-28]
 [8.89318317e-54 7.27336709e-54 7.21788305e-54]]
Iteration 1 | Cost: 0.500000
[[1.20283571e-25 1.05262460e-25 1.07730452e-25]
 [1.27603610e-43 8.79066637e-44 9.11744569e-44]
 [2.72179598e-43 1.61945846e-43 2.43037806e-43]
 ...
 [3.93397616e-39 2.91321460e-39 3.22890291e-39]
 [7.53246645e-28 6.53836945e-28 5.61762005e-28]
 [1.29837125e-53 8.68471217e-54 8.55271693e-54]]
Iteration 2 | Cost: 0.500000
[[1.41863348e-25 1.16137108e-25 1.20245397e-25]
 [1.74532960e-4

Iteration 226 | Cost: 49.307679
[[1.55086361e-09 4.23914119e-16 1.60774360e-15]
 [4.74846751e-13 5.21736082e-28 1.34307558e-27]
 [5.49206657e-14 6.30949887e-34 9.10900955e-21]
 ...
 [2.62360764e-13 5.18232008e-26 5.51861467e-23]
 [2.59448809e-08 7.49574627e-15 1.35635164e-20]
 [1.12195445e-16 2.67427187e-33 1.08188456e-34]]
Iteration 227 | Cost: 49.477790
[[1.81760670e-09 4.67468902e-16 1.76873015e-15]
 [6.39907982e-13 6.24563257e-28 1.60695418e-27]
 [7.38783660e-14 7.19001027e-34 1.11068868e-20]
 ...
 [3.38717377e-13 6.00288771e-26 6.47197929e-23]
 [3.12361307e-08 8.57825184e-15 1.49835716e-20]
 [1.60817545e-16 3.35439620e-33 1.34423711e-34]]
Iteration 228 | Cost: 49.709467
[[2.12774810e-09 5.15492907e-16 1.94566586e-15]
 [8.59975639e-13 7.47645823e-28 1.92237441e-27]
 [9.93159658e-14 8.19352163e-34 1.35358065e-20]
 ...
 [4.36564981e-13 6.95332473e-26 7.58858250e-23]
 [3.75046049e-08 9.81684767e-15 1.65532723e-20]
 [2.29726931e-16 4.20740073e-33 1.67003846e-34]]
Iteration 229 | Cost: 

Iteration 447 | Cost: 39.281224
[[5.10604551e-02 5.93169127e-08 4.01446099e-07]
 [5.18077959e-01 2.93332436e-13 7.18921097e-12]
 [4.87347916e-01 2.79727209e-19 8.92479944e-06]
 ...
 [1.15208083e-01 4.98537843e-13 2.47893459e-09]
 [2.14985585e-01 9.37187413e-06 7.58485387e-11]
 [3.16364946e-01 4.08979313e-15 4.78987151e-15]]
Iteration 448 | Cost: 38.904193
[[5.21288501e-02 6.39191732e-08 4.33818468e-07]
 [5.30218547e-01 3.34954784e-13 8.31045770e-12]
 [4.94608180e-01 3.30235135e-19 1.00482785e-05]
 ...
 [1.18346382e-01 5.64959643e-13 2.80240061e-09]
 [2.18816379e-01 1.00006982e-05 8.37175312e-11]
 [3.28383284e-01 4.80013290e-15 5.76340949e-15]]
Iteration 449 | Cost: 38.531535
[[5.31891199e-02 6.88757958e-08 4.68705228e-07]
 [5.42159282e-01 3.82455583e-13 9.60278374e-12]
 [5.01652124e-01 3.89847332e-19 1.13054485e-05]
 ...
 [1.21469022e-01 6.40193949e-13 3.16682039e-09]
 [2.22571460e-01 1.06710898e-05 9.23939453e-11]
 [3.40437575e-01 5.63331231e-15 6.93176395e-15]]
Iteration 450 | Cost: 

Iteration 695 | Cost: 0.732676
[[1.67376895e-01 2.30743424e-02 1.44159569e-02]
 [9.72995177e-01 2.36618584e-03 2.52824696e-03]
 [7.37499101e-01 1.96526642e-05 6.98775058e-01]
 ...
 [4.13103654e-01 2.01081114e-03 1.51645909e-02]
 [3.70131710e-01 1.40398672e-01 5.53722862e-04]
 [1.31240100e+00 2.04923216e-03 7.05021715e-04]]
Iteration 696 | Cost: 0.722716
[[1.67578833e-01 2.34848863e-02 1.46049186e-02]
 [9.72826151e-01 2.44397368e-03 2.59009303e-03]
 [7.37519677e-01 2.07721973e-05 7.01818585e-01]
 ...
 [4.13482343e-01 2.07737399e-03 1.54228054e-02]
 [3.70156676e-01 1.41657185e-01 5.67600948e-04]
 [1.31294019e+00 2.12394571e-03 7.27914209e-04]]
Iteration 697 | Cost: 0.712999
[[1.67779468e-01 2.38984095e-02 1.47950575e-02]
 [9.72657053e-01 2.52349744e-03 2.65298533e-03]
 [7.37539474e-01 2.19441112e-05 7.04835167e-01]
 ...
 [4.13858061e-01 2.14543875e-03 1.56834011e-02]
 [3.70181309e-01 1.42912084e-01 5.81734536e-04]
 [1.31347231e+00 2.20055717e-03 7.51371747e-04]]
Iteration 698 | Cost: 0.7

[[0.18989316 0.10655453 0.06777374]
 [0.94822543 0.03760815 0.03682754]
 [0.73583657 0.00268955 0.945188  ]
 ...
 [0.45140916 0.03312531 0.09571944]
 [0.37290953 0.28958252 0.01055766]
 [1.34831759 0.04023259 0.02271513]]
Iteration 925 | Cost: 0.251339
[[0.18992771 0.10669746 0.06795831]
 [0.94818147 0.03768595 0.03696659]
 [0.7358275  0.00270026 0.94517694]
 ...
 [0.45145835 0.03319703 0.09596641]
 [0.37291869 0.28976123 0.01060972]
 [1.34831952 0.04031305 0.02281819]]
Iteration 926 | Cost: 0.251122
[[0.18996199 0.1068389  0.06814202]
 [0.94813786 0.03776281 0.03710476]
 [0.73581848 0.00271087 0.9451626 ]
 ...
 [0.45150707 0.03326791 0.09621153]
 [0.37292785 0.28993815 0.0106616 ]
 [1.34832107 0.04039242 0.02292055]]
Iteration 927 | Cost: 0.250908
[[0.189996   0.10697885 0.06832486]
 [0.94809462 0.03783872 0.03724203]
 [0.7358095  0.00272137 0.94514505]
 ...
 [0.45155534 0.03333796 0.09645483]
 [0.372937   0.29011329 0.01071331]
 [1.34832225 0.04047069 0.02302221]]
Iteration 928 | Cos

In [174]:
y_pred = np.exp(np.dot(X_test, W))
rowsum = np.sum(y_pred, axis=1)
y_pred = y_pred/rowsum[:, None]
print(y_pred)
y_pred = np.argmax(y_pred, axis=1)
print(y_pred)


[[0.07771808 0.00251891 0.91976302]
 [0.93903753 0.01915841 0.04180406]
 [0.91685155 0.08024043 0.00290802]
 ...
 [0.85544589 0.06135011 0.083204  ]
 [0.58658736 0.0620052  0.35140744]
 [0.54170299 0.45676333 0.00153368]]
6239
